version: '3.6'
services:
  db:
    image: postgres:14.5-bullseye
    container_name: ompgsqlone
    environment:
      - container_name=ompgsqlone
      - POSTGRES_USER=onlinemagic
      - POSTGRES_DB=identityone
      - POSTGRES_PASSWORD=onlinemagic
      - PGDATA=/var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes: 
      - /pgdata/:/var/lib/postgresql/data
      # - ./db-seed-files/:/etc/docker-entrypoint-initdb.d      


  reverseproxy:
    build: ./nginx/
    container_name: reverseproxy 
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./static_volume:/var/www/static_volume

  certbot:
    image: certbot/certbot
    container_name: certbot

    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email "${CERT_MAIL}"  ${DOMAIN}  --agree-tos


  identityone:
    build: 
      context: ./Deployer/
      args:
        - repository=brijeshtd/IdentityOne.git
        - branch=master
        - dbmigration=1
        - DLL_RUNNER=IdentityOne.dll      
    container_name: identityone    
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - RUNNER=identityone.dll      
    depends_on:
      - db
    volumes: 
      - ./IdentityOne/appsettings.json:/app/appsettings.json
      - ./Keys/private-key.pem:/app/private-key.pem
      - ./Keys/public-key.pem:/app/public-key.pem

  omadmin:
    build:
      context: ./Deployer/
      args:
        - repository=brijeshtd/OmAdmin.git
        - branch=master
        - dbmigration=0
        - DLL_RUNNER=OmAdmin.dll 
    container_name: omadmin    
    depends_on:
      - db
    environment:
      - ASPNETCORE_URLS=http://+:5000
    volumes: 
      - ./OmAdmin/appsettings.json:/app/appsettings.json
      - ./Keys/public-key.pem:/app/public-key.pem
      - ./static_volume:/app/wwwroot/static

  omadminapi:
    build:
      context: ./Deployer/
      args:
        - repository=brijeshtd/OmAdminApi.git
        - branch=master      
        - dbmigration=1
        - DLL_RUNNER=OmAdminApi.dll         
    container_name: omadminapi   
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - RUNNER=OmAdminApi.dll      
    depends_on:
      - db
    volumes: 
      - ./OmAdminApi/appsettings.json:/app/appsettings.json
      - ./Keys/public-key.pem:/app/public-key.pem


  omcompany:
    build:
      context: ./Deployer/
      args:
        - repository=brijeshtd/OmCompany.git
        - branch=master
        - dbmigration=0
        - DLL_RUNNER=OmCompany.dll       
    container_name: omcompany      
    environment:
      - ASPNETCORE_URLS=http://+:5000           
    depends_on:
      - db
    volumes: 
      - ./OmCompany/appsettings.json:/app/appsettings.json
      - ./Keys/public-key.pem:/app/public-key.pem
      - ./static_volume:/app/wwwroot/static

  omcustomer:
    build:
      context: ./Deployer/
      args:
        - repository=brijeshtd/OmCustomer.git
        - branch=master
        - dbmigration=0
        - DLL_RUNNER=OmCustomer.dll            
    container_name: omcustomer 
    environment:
      - ASPNETCORE_URLS=http://+:5000             
    depends_on:
      - db
    volumes: 
      - ./OmCustomer/appsettings.json:/app/appsettings.json
      - ./Keys/public-key.pem:/app/public-key.pem
      - ./static_volume:/app/wwwroot/static

  omonboard:
    build:
      context: ./Deployer/
      args:
      - repository=brijeshtd/OmOnboard.git
      - branch=master
      - dbmigration=0
      - DLL_RUNNER=OmOnboard.dll  
    container_name: omonboard
    environment:
      - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - db
    volumes: 
      - ./OmOnboard/appsettings.json:/app/appsettings.json
      - ./Keys/public-key.pem:/app/public-key.pem
      - ./static_volume:/app/wwwroot/static


  omcarepackapi:
    build: ./OmCarePackApi/
    container_name: omcarepackapi
    command: ["dotnet","OmCarePackApi.dll"]
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - RUNNER=OmCarePackApi.dll
    depends_on:
      - db
    volumes: 
      - ./OmCarePackApi/appsettings.json:/app/appsettings.json
      - ./Keys/public-key.pem:/app/public-key.pem

  whatsappone:
    build: ./WhatsAppOne/
    container_name: whatsappone
    command: ["dotnet","WhatsAppOne.dll"]
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - RUNNER=WhatsAppOne.dll
    depends_on:
      - db
    volumes: 
      - ./WhatsAppOne/appsettings.json:/app/appsettings.json
      - ./Keys/public-key.pem:/app/public-key.pem

  ominventoryapi:
    build: ./OmInventoryApi/
    container_name: ominventoryapi
    command: ["dotnet","OmInventoryApi.dll"]    
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - RUNNER=OmInventoryApi.dll
    depends_on:
      - db
    volumes: 
      - ./OmInventoryApi/appsettings.json:/app/appsettings.json
      - ./Keys/public-key.pem:/app/public-key.pem

  omproductapi:
    build: ./OmProductApi/
    container_name: omproductapi
    command: ["dotnet","OmProductApi.dll"]  
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - RUNNER=OmProductApi.dll
    depends_on:
      - db
    volumes: 
      - ./OmProductApi/appsettings.json:/app/appsettings.json
      - ./Keys/public-key.pem:/app/public-key.pem

  omcustomerapi:
    build: ./OmCustomerApi/
    container_name: omcustomerapi
    command: ["dotnet","OmCustomerApi.dll"]      
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - RUNNER=OmCustomerApi.dll
    depends_on:
      - db
    volumes: 
      - ./OmCustomerApi/appsettings.json:/app/appsettings.json
      - ./Keys/public-key.pem:/app/public-key.pem

  omemailapi:
    build: ./OmEmailApi/
    container_name: omemailapi
    command: ["dotnet","OmEmailApi.dll"]      
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - RUNNER=OmEmailApi.dll
    depends_on:
      - db
    volumes: 
      - ./OmEmailApi/appsettings.json:/app/appsettings.json
      - ./Keys/public-key.pem:/app/public-key.pem

  omnotificationapi:
    build: ./OmNotificationApi/
    container_name: omnotificationapi
    command: ["dotnet","OmNotificationApi.dll"]  
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - RUNNER=OmNotificationApi.dll
    depends_on:
      - db
    volumes: 
      - ./OmNotificationApi/appsettings.json:/app/appsettings.json
      - ./Keys/public-key.pem:/app/public-key.pem

  omwhatsappwebhook:
    build: ./OmWhatsappWebhook/
    container_name: omwhatsappwebhook
    command: ["dotnet","OmWhatsappWebhook.dll"]  
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - RUNNER=OmWhatsappWebhook.dll
    depends_on:
      - db
    volumes: 
      - ./OmWhatsappWebhook/appsettings.json:/app/appsettings.json
      - ./Keys/public-key.pem:/app/public-key.pem

  omwhatsappapi:
    build: ./OmWhatsappApi/
    container_name: omwhatsappapi
    command: ["dotnet","OmWhatsappApi.dll"]      
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - RUNNER=OmWhatsappApi.dll
    depends_on:
      - db
    volumes: 
      - ./OmWhatsappApi/appsettings.json:/app/appsettings.json
      - ./Keys/public-key.pem:/app/public-key.pem

  omserviceapi:
    build: ./OmServiceApi/
    container_name: omserviceapi
    command: ["dotnet","OmServiceApi.dll"]      
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - RUNNER=OmServiceApi.dll
    depends_on:
      - db
    volumes: 
      - ./OmServiceApi/appsettings.json:/app/appsettings.json
      - ./Keys/public-key.pem:/app/public-key.pem
  
