version: '3.6'
services:
  db:
    image: postgres:14.5-bullseye
    container_name: ompgsqlone
    environment:
      - container_name=ompgsqlone
      - POSTGRES_USER=onlinemagic
      - POSTGRES_DB=identityone
      - POSTGRES_PASSWORD=onlinemagic
      - PGDATA=/var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes: 
      - /pgdata/:/var/lib/postgresql/data
      # - ./db-seed-files/:/etc/docker-entrypoint-initdb.d      
  rqueue:

    image: rabbitmq:3.11-management
    container_name: rqueue

    environment:
      - RABBITMQ_DEFAULT_USER=magicQ
      - RABBITMQ_DEFAULT_PASS=onlineQfortesting2022
    ports:
      - 15672:15672
      - 5672:5672


  reverseproxy:
    build: ./nginx/
    container_name: reverseproxy 
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./static_volume:/var/www/static_volume

  certbot:
    image: certbot/certbot
    container_name: certbot

    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email "${CERT_MAIL}"  ${DOMAIN}  --agree-tos


  identityone:
    build: 
      context: ./Deployer/
      args:
        - repository=brijeshtd/IdentityOne.git
        - branch=master
        - dbmigration=1
        - DLL_RUNNER=IdentityOne.dll      
    container_name: identityone    
    environment:
      - ASPNETCORE_URLS=http://+:5000    
    depends_on:
      - db
    volumes: 
      - ./IdentityOne/appsettings.json:/app/appsettings.json
      - ./Deployer/private-key.pem:/app/private-key.pem
 #     - ./Keys/public-key.pem:/app/public-key.pem

  omadmin:
    build:
      context: ./Deployer/
      args:
        - repository=brijeshtd/OmAdmin.git
        - branch=master
        - dbmigration=0
        - DLL_RUNNER=OmAdmin.dll 
    container_name: omadmin    
    depends_on:
      - db
    environment:
      - ASPNETCORE_URLS=http://+:5000
    volumes: 
      - ./OmAdmin/appsettings.json:/app/appsettings.json
 #     - ./Keys/public-key.pem:/app/public-key.pem
      - ./static_volume:/app/wwwroot/static

  omadminapi:
    build:
      context: ./Deployer/
      args:
        - repository=brijeshtd/OmAdminApi.git
        - branch=master      
        - dbmigration=1
        - DLL_RUNNER=OmAdminApi.dll         
    container_name: omadminapi   
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - RUNNER=OmAdminApi.dll      
    depends_on:
      - db
    volumes: 
      - ./OmAdminApi/appsettings.json:/app/appsettings.json
 #     - ./Keys/public-key.pem:/app/public-key.pem
  omcompany:
    build:
      context: ./Deployer/
      args:
        - repository=brijeshtd/OmCompany.git
        - branch=master
        - dbmigration=0
        - DLL_RUNNER=OmCompany.dll       
    container_name: omcompany      
    environment:
      - ASPNETCORE_URLS=http://+:5000           
    depends_on:
      - db
    volumes: 
      - ./OmCompany/appsettings.json:/app/appsettings.json
 #     - ./Keys/public-key.pem:/app/public-key.pem
      - ./static_volume:/app/wwwroot/static

  omcustomer:
    build:
      context: ./Deployer/
      args:
        - repository=brijeshtd/OmCustomer.git
        - branch=master
        - dbmigration=0
        - DLL_RUNNER=OmCustomer.dll            
    container_name: omcustomer 
    environment:
      - ASPNETCORE_URLS=http://+:5000             
    depends_on:
      - db
    volumes: 
      - ./OmCustomer/appsettings.json:/app/appsettings.json
 #     - ./Keys/public-key.pem:/app/public-key.pem
      - ./static_volume:/app/wwwroot/static

  omonboard:
    build:
      context: ./Deployer/
      args:
      - repository=brijeshtd/OmOnboard.git
      - branch=master
      - dbmigration=0
      - DLL_RUNNER=OmOnboard.dll  
    container_name: omonboard
    environment:
      - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - db
    volumes: 
      - ./OmOnboard/appsettings.json:/app/appsettings.json
 #     - ./Keys/public-key.pem:/app/public-key.pem
      - ./static_volume:/app/wwwroot/static

  omcarepackapi:
    build:
      context: ./Deployer/
      args:
      - repository=brijeshtd/OmCarePackApi.git
      - branch=master
      - dbmigration=0
      - DLL_RUNNER=OmCarePackApi.dll

    container_name: omcarepackapi
    # command: ["dotnet","OmCarePackApi.dll"]
    environment:
      - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - db
    volumes:
      - ./OmCarePackApi/appsettings.json:/app/appsettings.json
 #     - ./Keys/public-key.pem:/app/public-key.pem

  ominventoryapi:
    build:
      context: ./Deployer/
      args:
      - repository=brijeshtd/OmInventoryApi.git
      - branch=master
      - dbmigration=0
      - DLL_RUNNER=OmInventoryApi.dll  
    container_name: ominventoryapi
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - RUNNER=OmInventoryApi.dll
    depends_on:
      - db
    volumes:
      - ./OmInventoryApi/appsettings.json:/app/appsettings.json
 #     - ./Keys/public-key.pem:/app/public-key.pem

  omproductapi:
    build:
      context: ./Deployer/
      args:
      - repository=brijeshtd/OmProductApi.git
      - branch=master
      - dbmigration=0
      - DLL_RUNNER=OmProductApi.dll  
    container_name: omproductapi
    environment:
      - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - db
    volumes:
      - ./OmProductApi/appsettings.json:/app/appsettings.json
 #     - ./Keys/public-key.pem:/app/public-key.pem

  omcustomerapi:
    build: 
      context: ./Deployer/
      args:
      - repository=brijeshtd/OmCustomerApi.git
      - branch=master
      - dbmigration=0
      - DLL_RUNNER=OmCustomerApi.dll  
    container_name: omcustomerapi
    environment:
      - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - db
    volumes:
      - ./OmCustomerApi/appsettings.json:/app/appsettings.json
 #     - ./Keys/public-key.pem:/app/public-key.pem

  omemailapi:
    build: 
      context: ./Deployer/
      args:
      - repository=brijeshtd/OmEmailApi.git
      - branch=master
      - dbmigration=0
      - DLL_RUNNER=OmEmailApi.dll  
    container_name: omemailapi
    environment:
      - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - db
    volumes:
      - ./OmEmailApi/appsettings.json:/app/appsettings.json
 #     - ./Keys/public-key.pem:/app/public-key.pem

  omnotificationapi:
    build: 
      context: ./Deployer/
      args:
      - repository=brijeshtd/OmNotificationApi.git
      - branch=master
      - dbmigration=0
      - DLL_RUNNER=OmNotificationApi.dll  
    container_name: omnotificationapi
    environment:
      - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - db
    volumes:
      - ./OmNotificationApi/appsettings.json:/app/appsettings.json
 #     - ./Keys/public-key.pem:/app/public-key.pem

  omwhatsappwebhook:
    build: 
      context: ./Deployer/
      args:
      - repository=brijeshtd/OmWhatsappWebhook.git
      - branch=master
      - dbmigration=0
      - DLL_RUNNER=OmWhatsappWebhook.dll  
    container_name: omwhatsappwebhook
    environment:
      - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - db
    volumes:
      - ./OmWhatsappWebhook/appsettings.json:/app/appsettings.json
 #     - ./Keys/public-key.pem:/app/public-key.pem

  omwhatsappapi:
    build: 
      context: ./Deployer/
      args:
      - repository=brijeshtd/OmWhatsappApi.git
      - branch=master
      - dbmigration=0
      - DLL_RUNNER=OmWhatsappApi.dll  
    container_name: omwhatsappapi
    environment:
      - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - db
    volumes:
      - ./OmWhatsappApi/appsettings.json:/app/appsettings.json
 #     - ./Keys/public-key.pem:/app/public-key.pem

  omserviceapi:
    build: 
      context: ./Deployer/
      args:
      - repository=brijeshtd/OmServiceApi.git
      - branch=master
      - dbmigration=0
      - DLL_RUNNER=OmServiceApi.dll  
    container_name: omserviceapi
    environment:
      - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - db
    volumes:
      - ./OmServiceApi/appsettings.json:/app/appsettings.json
 #     - ./Keys/public-key.pem:/app/public-key.pem
