CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE address_types (
    address_type_id bigint GENERATED BY DEFAULT AS IDENTITY,
    entity_name character varying(50) NOT NULL,
    address_type_name character varying(50) NOT NULL,
    CONSTRAINT "PK_address_types" PRIMARY KEY (address_type_id)
);

CREATE TABLE banks (
    bank_id bigint GENERATED BY DEFAULT AS IDENTITY,
    bank_name character varying(50) NOT NULL,
    record_status character varying(50) NOT NULL,
    CONSTRAINT "PK_banks" PRIMARY KEY (bank_id)
);

CREATE TABLE certification_levels (
    certification_level_id bigint GENERATED BY DEFAULT AS IDENTITY,
    certification_level character varying(50) NOT NULL,
    level_no integer NOT NULL,
    CONSTRAINT "PK_certification_levels" PRIMARY KEY (certification_level_id)
);

CREATE TABLE company_levels (
    company_level_id bigint GENERATED BY DEFAULT AS IDENTITY,
    company_level character varying(50) NOT NULL,
    level_no integer NOT NULL,
    CONSTRAINT "PK_company_levels" PRIMARY KEY (company_level_id)
);

CREATE TABLE company_types (
    company_type_id bigint GENERATED BY DEFAULT AS IDENTITY,
    company_type_name character varying(50) NOT NULL,
    CONSTRAINT "PK_company_types" PRIMARY KEY (company_type_id)
);

CREATE TABLE countries (
    country_id bigint GENERATED BY DEFAULT AS IDENTITY,
    country_name character varying(50) NOT NULL,
    country_code character varying(3) NOT NULL,
    record_status character varying(50) NOT NULL,
    CONSTRAINT "PK_countries" PRIMARY KEY (country_id)
);

CREATE TABLE designations (
    designation_id bigint GENERATED BY DEFAULT AS IDENTITY,
    designation_name character varying(50) NOT NULL,
    designation_code character varying(5) NOT NULL,
    record_status character varying(50) NOT NULL,
    created_by bigint NOT NULL,
    created_on timestamp NOT NULL,
    updated_by bigint NOT NULL,
    updated_on timestamp NOT NULL,
    CONSTRAINT "PK_designations" PRIMARY KEY (designation_id)
);

CREATE TABLE domains (
    domain_id bigint GENERATED BY DEFAULT AS IDENTITY,
    domain_name character varying(50) NOT NULL,
    CONSTRAINT "PK_domains" PRIMARY KEY (domain_id)
);

CREATE TABLE notifications (
    notification_id bigint GENERATED BY DEFAULT AS IDENTITY,
    notification character varying(250) NOT NULL,
    action_name character varying(50) NOT NULL,
    link_name character varying(250) NOT NULL,
    record_status character varying(50) NOT NULL,
    created timestamp NOT NULL,
    expiry timestamp NOT NULL DEFAULT TIMESTAMP '2022-11-15 14:54:00.935446',
    closed_on character varying(25) NOT NULL DEFAULT 'NA',
    account_id bigint NOT NULL DEFAULT 0,
    closed_by bigint NOT NULL DEFAULT 0,
    CONSTRAINT "PK_notifications" PRIMARY KEY (notification_id)
);

CREATE TABLE product_categories (
    product_category_id bigint GENERATED BY DEFAULT AS IDENTITY,
    product_category_name character varying(50) NOT NULL,
    CONSTRAINT "PK_product_categories" PRIMARY KEY (product_category_id)
);

CREATE TABLE qualification_levels (
    qualification_level_id bigint GENERATED BY DEFAULT AS IDENTITY,
    qualification_level character varying(50) NOT NULL,
    level_no integer NOT NULL,
    CONSTRAINT "PK_qualification_levels" PRIMARY KEY (qualification_level_id)
);

CREATE TABLE technologies (
    technology_id bigint GENERATED BY DEFAULT AS IDENTITY,
    technology_name character varying(50) NOT NULL,
    record_status character varying(50) NOT NULL,
    created_by bigint NOT NULL,
    created_on timestamp NOT NULL,
    updated_by bigint NOT NULL,
    updated_on timestamp NOT NULL,
    CONSTRAINT "PK_technologies" PRIMARY KEY (technology_id)
);

CREATE TABLE time_units (
    time_unit_id bigint GENERATED BY DEFAULT AS IDENTITY,
    time_unit character varying(100) NOT NULL,
    CONSTRAINT "PK_time_units" PRIMARY KEY (time_unit_id)
);

CREATE TABLE verticals (
    vertical_id bigint GENERATED BY DEFAULT AS IDENTITY,
    vertical_name character varying(50) NOT NULL,
    CONSTRAINT "PK_verticals" PRIMARY KEY (vertical_id)
);

CREATE TABLE companies (
    company_id bigint GENERATED BY DEFAULT AS IDENTITY,
    company_name character varying(50) NOT NULL,
    company_code character varying(250) NOT NULL,
    branch_name character varying(50) NOT NULL,
    gst character varying(15) NOT NULL,
    pan character varying(10) NOT NULL,
    email character varying(50) NOT NULL,
    mobile character varying(10) NOT NULL,
    contact_person character varying(50) NOT NULL,
    total_forms integer NOT NULL,
    form_completed integer NOT NULL,
    company_status character varying(50) NOT NULL,
    record_status character varying(50) NOT NULL,
    created_by bigint NOT NULL,
    created_on timestamp NOT NULL,
    updated_by bigint NOT NULL,
    updated_on timestamp NOT NULL,
    company_level_id bigint NOT NULL,
    company_type_id bigint NOT NULL,
    CONSTRAINT "PK_companies" PRIMARY KEY (company_id),
    CONSTRAINT "FK_companies_company_levels_company_level_id" FOREIGN KEY (company_level_id) REFERENCES company_levels (company_level_id) ON DELETE CASCADE,
    CONSTRAINT "FK_companies_company_types_company_type_id" FOREIGN KEY (company_type_id) REFERENCES company_types (company_type_id) ON DELETE CASCADE
);

CREATE TABLE states (
    state_id bigint GENERATED BY DEFAULT AS IDENTITY,
    state_name character varying(50) NOT NULL,
    state_code character varying(50) NOT NULL,
    record_status character varying(50) NOT NULL,
    country_id bigint NOT NULL,
    CONSTRAINT "PK_states" PRIMARY KEY (state_id),
    CONSTRAINT "FK_states_countries_country_id" FOREIGN KEY (country_id) REFERENCES countries (country_id) ON DELETE CASCADE
);

CREATE TABLE product_types (
    product_type_id bigint GENERATED BY DEFAULT AS IDENTITY,
    product_type_name character varying(50) NOT NULL,
    product_category_id bigint NOT NULL,
    CONSTRAINT "PK_product_types" PRIMARY KEY (product_type_id),
    CONSTRAINT "FK_product_types_product_categories_product_category_id" FOREIGN KEY (product_category_id) REFERENCES product_categories (product_category_id) ON DELETE CASCADE
);

CREATE TABLE qualifications (
    qualification_id bigint GENERATED BY DEFAULT AS IDENTITY,
    qualification_name character varying(50) NOT NULL,
    qualification_code character varying(10) NOT NULL,
    record_status character varying(50) NOT NULL,
    created_by bigint NOT NULL,
    created_on timestamp NOT NULL,
    updated_by bigint NOT NULL,
    updated_on timestamp NOT NULL,
    qualification_level_id bigint NOT NULL,
    CONSTRAINT "PK_qualifications" PRIMARY KEY (qualification_id),
    CONSTRAINT "FK_qualifications_qualification_levels_qualification_level_id" FOREIGN KEY (qualification_level_id) REFERENCES qualification_levels (qualification_level_id) ON DELETE CASCADE
);

CREATE TABLE certifications (
    certification_id bigint GENERATED BY DEFAULT AS IDENTITY,
    certification_name character varying(50) NOT NULL,
    certification_code character varying(10) NOT NULL,
    certified_by character varying(50) NOT NULL,
    record_status character varying(50) NOT NULL,
    created_by bigint NOT NULL,
    created_on timestamp NOT NULL,
    updated_by bigint NOT NULL,
    updated_on timestamp NOT NULL,
    certification_level_id bigint NOT NULL,
    technology_id bigint NOT NULL,
    CONSTRAINT "PK_certifications" PRIMARY KEY (certification_id),
    CONSTRAINT "FK_certifications_certification_levels_certification_level_id" FOREIGN KEY (certification_level_id) REFERENCES certification_levels (certification_level_id) ON DELETE CASCADE,
    CONSTRAINT "FK_certifications_technologies_technology_id" FOREIGN KEY (technology_id) REFERENCES technologies (technology_id) ON DELETE CASCADE
);

CREATE TABLE company_banks (
    company_bank_id bigint GENERATED BY DEFAULT AS IDENTITY,
    branch character varying(50) NOT NULL,
    ifsc character varying(50) NOT NULL,
    account_no character varying(50) NOT NULL,
    record_status character varying(50) NOT NULL,
    created_by bigint NOT NULL,
    created_on timestamp NOT NULL,
    updated_by bigint NOT NULL,
    updated_on timestamp NOT NULL,
    company_id bigint NOT NULL,
    bank_id bigint NOT NULL,
    CONSTRAINT "PK_company_banks" PRIMARY KEY (company_bank_id),
    CONSTRAINT "FK_company_banks_banks_bank_id" FOREIGN KEY (bank_id) REFERENCES banks (bank_id) ON DELETE CASCADE,
    CONSTRAINT "FK_company_banks_companies_company_id" FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE
);

CREATE TABLE company_contacts (
    company_contact_id bigint GENERATED BY DEFAULT AS IDENTITY,
    contact_person character varying(50) NOT NULL,
    contact_number character varying(50) NOT NULL,
    record_status character varying(50) NOT NULL,
    created_by bigint NOT NULL,
    created_on timestamp NOT NULL,
    updated_by bigint NOT NULL,
    updated_on timestamp NOT NULL,
    company_id bigint NOT NULL,
    CONSTRAINT "PK_company_contacts" PRIMARY KEY (company_contact_id),
    CONSTRAINT "FK_company_contacts_companies_company_id" FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE
);

CREATE TABLE company_departments (
    department_id bigint GENERATED BY DEFAULT AS IDENTITY,
    department_name character varying(50) NOT NULL,
    record_status character varying(50) NOT NULL,
    created_by bigint NOT NULL,
    created_on timestamp NOT NULL,
    updated_by bigint NOT NULL,
    updated_on timestamp NOT NULL,
    company_id bigint NOT NULL,
    CONSTRAINT "PK_company_departments" PRIMARY KEY (department_id),
    CONSTRAINT "FK_company_departments_companies_company_id" FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE
);

CREATE TABLE company_domains (
    company_domain_id bigint GENERATED BY DEFAULT AS IDENTITY,
    company_id bigint NOT NULL,
    domain_id bigint NOT NULL,
    record_status character varying(50) NOT NULL,
    created_by bigint NOT NULL,
    created_on timestamp NOT NULL,
    updated_by bigint NOT NULL,
    updated_on timestamp NOT NULL,
    CONSTRAINT "PK_company_domains" PRIMARY KEY (company_domain_id),
    CONSTRAINT "FK_company_domains_companies_company_id" FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE,
    CONSTRAINT "FK_company_domains_domains_domain_id" FOREIGN KEY (domain_id) REFERENCES domains (domain_id) ON DELETE CASCADE
);

CREATE TABLE company_onboardings (
    onboarding_id bigint GENERATED BY DEFAULT AS IDENTITY,
    tracking_id character varying(250) NOT NULL,
    entity character varying(50) NOT NULL,
    email character varying(100) NOT NULL,
    mobile character varying(15) NOT NULL,
    email_status character varying(50) NOT NULL,
    mobile_status character varying(50) NOT NULL,
    onboard_status character varying(50) NOT NULL,
    record_status character varying(50) NOT NULL,
    created_by bigint NOT NULL,
    created_on timestamp NOT NULL,
    updated_by bigint NOT NULL,
    updated_on timestamp NOT NULL,
    expires_on timestamp NOT NULL,
    account_id bigint NOT NULL,
    company_id bigint NOT NULL,
    company_level_id bigint NOT NULL,
    CONSTRAINT "PK_company_onboardings" PRIMARY KEY (onboarding_id),
    CONSTRAINT "FK_company_onboardings_companies_company_id" FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE,
    CONSTRAINT "FK_company_onboardings_company_levels_company_level_id" FOREIGN KEY (company_level_id) REFERENCES company_levels (company_level_id) ON DELETE CASCADE
);

CREATE TABLE company_verticals (
    company_vertical_id bigint GENERATED BY DEFAULT AS IDENTITY,
    company_id bigint NOT NULL,
    vertical_id bigint NOT NULL,
    parent_id bigint NOT NULL,
    record_status character varying(50) NOT NULL,
    created_by bigint NOT NULL,
    created_on timestamp NOT NULL,
    updated_by bigint NOT NULL,
    updated_on timestamp NOT NULL,
    CONSTRAINT "PK_company_verticals" PRIMARY KEY (company_vertical_id),
    CONSTRAINT "FK_company_verticals_companies_company_id" FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE,
    CONSTRAINT "FK_company_verticals_verticals_vertical_id" FOREIGN KEY (vertical_id) REFERENCES verticals (vertical_id) ON DELETE CASCADE
);

CREATE TABLE customers (
    customer_id bigint GENERATED BY DEFAULT AS IDENTITY,
    customer_code character varying(20) NOT NULL,
    first_name character varying(50) NOT NULL,
    middle_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    customer_type character varying(20) NOT NULL,
    gender character varying(10) NOT NULL,
    dob timestamp with time zone NOT NULL,
    gst character varying(15) NOT NULL,
    pan character varying(10) NOT NULL,
    aadhar character varying(12) NOT NULL,
    email character varying(50) NOT NULL,
    mobile character varying(20) NOT NULL,
    customer_status character varying(50) NOT NULL,
    total_forms integer NOT NULL,
    form_completed integer NOT NULL,
    record_status character varying(50) NOT NULL,
    created_by bigint NOT NULL,
    created_on timestamp NOT NULL,
    updated_by bigint NOT NULL,
    updated_on timestamp NOT NULL,
    account_id bigint NOT NULL,
    company_id bigint NOT NULL,
    CONSTRAINT "PK_customers" PRIMARY KEY (customer_id),
    CONSTRAINT "FK_customers_companies_company_id" FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE
);

CREATE TABLE employees (
    employee_id bigint GENERATED BY DEFAULT AS IDENTITY,
    employee_code character varying(250) NOT NULL,
    first_name character varying(50) NOT NULL,
    middle_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    gender character varying(10) NOT NULL,
    dob timestamp with time zone NOT NULL,
    pan character varying(10) NOT NULL,
    aadhar character varying(12) NOT NULL,
    email character varying(50) NOT NULL,
    mobile character varying(20) NOT NULL,
    doj timestamp with time zone NOT NULL,
    dol character varying(10) NULL,
    dol_reason character varying(50) NOT NULL DEFAULT 'NA',
    dol_remarks character varying(250) NOT NULL DEFAULT 'NA',
    employee_status character varying(50) NOT NULL,
    total_forms integer NOT NULL,
    form_completed integer NOT NULL,
    record_status character varying(50) NOT NULL,
    created_by bigint NOT NULL,
    created_on timestamp NOT NULL,
    updated_by bigint NOT NULL,
    updated_on timestamp NOT NULL,
    account_id bigint NOT NULL,
    company_id bigint NOT NULL,
    designation_id bigint NOT NULL,
    CONSTRAINT "PK_employees" PRIMARY KEY (employee_id),
    CONSTRAINT "FK_employees_companies_company_id" FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE,
    CONSTRAINT "FK_employees_designations_designation_id" FOREIGN KEY (designation_id) REFERENCES designations (designation_id) ON DELETE CASCADE
);

CREATE TABLE districts (
    district_id bigint GENERATED BY DEFAULT AS IDENTITY,
    district_name character varying(50) NOT NULL,
    district_code character varying(50) NOT NULL,
    record_status character varying(50) NOT NULL,
    created_by bigint NOT NULL,
    created_on timestamp NOT NULL,
    updated_by bigint NOT NULL,
    updated_on timestamp NOT NULL,
    state_id bigint NOT NULL,
    CONSTRAINT "PK_districts" PRIMARY KEY (district_id),
    CONSTRAINT "FK_districts_states_state_id" FOREIGN KEY (state_id) REFERENCES states (state_id) ON DELETE CASCADE
);

CREATE TABLE specializations (
    specialization_id bigint GENERATED BY DEFAULT AS IDENTITY,
    specialization_name character varying(50) NOT NULL,
    record_status character varying(50) NOT NULL,
    created_by bigint NOT NULL,
    created_on timestamp NOT NULL,
    updated_by bigint NOT NULL,
    updated_on timestamp NOT NULL,
    qualification_id bigint NOT NULL,
    CONSTRAINT "PK_specializations" PRIMARY KEY (specialization_id),
    CONSTRAINT "FK_specializations_qualifications_qualification_id" FOREIGN KEY (qualification_id) REFERENCES qualifications (qualification_id) ON DELETE CASCADE
);

CREATE TABLE divisions (
    division_id bigint GENERATED BY DEFAULT AS IDENTITY,
    division_name character varying(50) NOT NULL,
    record_status character varying(50) NOT NULL,
    created_by bigint NOT NULL,
    created_on timestamp NOT NULL,
    updated_by bigint NOT NULL,
    updated_on timestamp NOT NULL,
    department_id bigint NOT NULL,
    CONSTRAINT "PK_divisions" PRIMARY KEY (division_id),
    CONSTRAINT "FK_divisions_company_departments_department_id" FOREIGN KEY (department_id) REFERENCES company_departments (department_id) ON DELETE CASCADE
);

CREATE TABLE onboarding_transactions (
    onboarding_transaction_id bigint GENERATED BY DEFAULT AS IDENTITY,
    tracking_id character varying(250) NOT NULL,
    sent_from character varying(100) NOT NULL,
    sent_to character varying(100) NOT NULL,
    action_name character varying(50) NOT NULL,
    action_status character varying(50) NOT NULL,
    remarks character varying(250) NOT NULL,
    created_on timestamp NOT NULL,
    onboarding_id bigint NOT NULL,
    CONSTRAINT "PK_onboarding_transactions" PRIMARY KEY (onboarding_transaction_id),
    CONSTRAINT "FK_onboarding_transactions_company_onboardings_onboarding_id" FOREIGN KEY (onboarding_id) REFERENCES company_onboardings (onboarding_id) ON DELETE CASCADE
);

CREATE TABLE complaints (
    complaint_id bigint GENERATED BY DEFAULT AS IDENTITY,
    nature_of_complaint character varying(100) NOT NULL,
    complaint_description character varying(250) NOT NULL,
    complaint_status character varying(50) NOT NULL,
    record_status character varying(50) NOT NULL,
    created_by bigint NOT NULL,
    created_on timestamp NOT NULL,
    updated_by bigint NOT NULL,
    updated_on timestamp NOT NULL,
    customer_id bigint NOT NULL,
    product_type_id bigint NOT NULL,
    CONSTRAINT "PK_complaints" PRIMARY KEY (complaint_id),
    CONSTRAINT "FK_complaints_customers_customer_id" FOREIGN KEY (customer_id) REFERENCES customers (customer_id) ON DELETE CASCADE,
    CONSTRAINT "FK_complaints_product_types_product_type_id" FOREIGN KEY (product_type_id) REFERENCES product_types (product_type_id) ON DELETE CASCADE
);

CREATE TABLE customer_banks (
    customer_bank_id bigint GENERATED BY DEFAULT AS IDENTITY,
    branch character varying(50) NOT NULL,
    ifsc character varying(50) NOT NULL,
    account_no character varying(50) NOT NULL,
    record_status character varying(50) NOT NULL,
    created_by bigint NOT NULL,
    created_on timestamp NOT NULL,
    updated_by bigint NOT NULL,
    updated_on timestamp NOT NULL,
    customer_id bigint NOT NULL,
    bank_id bigint NOT NULL,
    CONSTRAINT "PK_customer_banks" PRIMARY KEY (customer_bank_id),
    CONSTRAINT "FK_customer_banks_banks_bank_id" FOREIGN KEY (bank_id) REFERENCES banks (bank_id) ON DELETE CASCADE,
    CONSTRAINT "FK_customer_banks_customers_customer_id" FOREIGN KEY (customer_id) REFERENCES customers (customer_id) ON DELETE CASCADE
);

CREATE TABLE employee_banks (
    employee_bank_id bigint GENERATED BY DEFAULT AS IDENTITY,
    branch character varying(50) NOT NULL,
    ifsc character varying(50) NOT NULL,
    account_no character varying(50) NOT NULL,
    record_status character varying(50) NOT NULL,
    created_by bigint NOT NULL,
    created_on timestamp NOT NULL,
    updated_by bigint NOT NULL,
    updated_on timestamp NOT NULL,
    employee_id bigint NOT NULL,
    bank_id bigint NOT NULL,
    CONSTRAINT "PK_employee_banks" PRIMARY KEY (employee_bank_id),
    CONSTRAINT "FK_employee_banks_banks_bank_id" FOREIGN KEY (bank_id) REFERENCES banks (bank_id) ON DELETE CASCADE,
    CONSTRAINT "FK_employee_banks_employees_employee_id" FOREIGN KEY (employee_id) REFERENCES employees (employee_id) ON DELETE CASCADE
);

CREATE TABLE employee_certifications (
    employee_certification_id bigint GENERATED BY DEFAULT AS IDENTITY,
    year_of_completion integer NOT NULL,
    record_status character varying(50) NOT NULL,
    created_by bigint NOT NULL,
    created_on timestamp NOT NULL,
    updated_by bigint NOT NULL,
    updated_on timestamp NOT NULL,
    employee_id bigint NOT NULL,
    certification_id bigint NOT NULL,
    CONSTRAINT "PK_employee_certifications" PRIMARY KEY (employee_certification_id),
    CONSTRAINT "FK_employee_certifications_certifications_certification_id" FOREIGN KEY (certification_id) REFERENCES certifications (certification_id) ON DELETE CASCADE,
    CONSTRAINT "FK_employee_certifications_employees_employee_id" FOREIGN KEY (employee_id) REFERENCES employees (employee_id) ON DELETE CASCADE
);

CREATE TABLE employee_work_experiences (
    employee_experience_id bigint GENERATED BY DEFAULT AS IDENTITY,
    company_name character varying(50) NOT NULL,
    from_date timestamp with time zone NOT NULL,
    to_date timestamp with time zone NOT NULL,
    reason_for_leaving character varying(50) NOT NULL,
    record_status character varying(50) NOT NULL,
    created_by bigint NOT NULL,
    created_on timestamp NOT NULL,
    updated_by bigint NOT NULL,
    updated_on timestamp NOT NULL,
    employee_id bigint NOT NULL,
    vertical_id bigint NOT NULL,
    designation_id bigint NOT NULL,
    CONSTRAINT "PK_employee_work_experiences" PRIMARY KEY (employee_experience_id),
    CONSTRAINT "FK_employee_work_experiences_designations_designation_id" FOREIGN KEY (designation_id) REFERENCES designations (designation_id) ON DELETE CASCADE,
    CONSTRAINT "FK_employee_work_experiences_employees_employee_id" FOREIGN KEY (employee_id) REFERENCES employees (employee_id) ON DELETE CASCADE,
    CONSTRAINT "FK_employee_work_experiences_verticals_vertical_id" FOREIGN KEY (vertical_id) REFERENCES verticals (vertical_id) ON DELETE CASCADE
);

CREATE TABLE post_offices (
    post_office_id bigint GENERATED BY DEFAULT AS IDENTITY,
    post_office_name character varying(50) NOT NULL,
    pin_code character varying(6) NOT NULL,
    latitude double precision NOT NULL DEFAULT 0.0,
    longitude double precision NOT NULL DEFAULT 0.0,
    record_status character varying(50) NOT NULL,
    created_by bigint NOT NULL,
    created_on timestamp NOT NULL,
    updated_by bigint NOT NULL,
    updated_on timestamp NOT NULL,
    district_id bigint NOT NULL,
    CONSTRAINT "PK_post_offices" PRIMARY KEY (post_office_id),
    CONSTRAINT "FK_post_offices_districts_district_id" FOREIGN KEY (district_id) REFERENCES districts (district_id) ON DELETE CASCADE
);

CREATE TABLE employee_qualifications (
    employee_qualification_id bigint GENERATED BY DEFAULT AS IDENTITY,
    college_name character varying(50) NOT NULL,
    duration double precision NOT NULL,
    course_type character varying(50) NOT NULL,
    year_of_completion integer NOT NULL,
    record_status character varying(50) NOT NULL,
    created_by bigint NOT NULL,
    created_on timestamp NOT NULL,
    updated_by bigint NOT NULL,
    updated_on timestamp NOT NULL,
    employee_id bigint NOT NULL,
    specialization_id bigint NOT NULL,
    time_unit_id bigint NOT NULL,
    CONSTRAINT "PK_employee_qualifications" PRIMARY KEY (employee_qualification_id),
    CONSTRAINT "FK_employee_qualifications_employees_employee_id" FOREIGN KEY (employee_id) REFERENCES employees (employee_id) ON DELETE CASCADE,
    CONSTRAINT "FK_employee_qualifications_specializations_specialization_id" FOREIGN KEY (specialization_id) REFERENCES specializations (specialization_id) ON DELETE CASCADE,
    CONSTRAINT "FK_employee_qualifications_time_units_time_unit_id" FOREIGN KEY (time_unit_id) REFERENCES time_units (time_unit_id) ON DELETE CASCADE
);

CREATE TABLE division_employees (
    employee_division_id bigint GENERATED BY DEFAULT AS IDENTITY,
    record_status character varying(50) NOT NULL,
    created_by bigint NOT NULL,
    created_on timestamp NOT NULL,
    updated_by bigint NOT NULL,
    updated_on timestamp NOT NULL,
    division_id bigint NOT NULL,
    employee_id bigint NOT NULL,
    CONSTRAINT "PK_division_employees" PRIMARY KEY (employee_division_id),
    CONSTRAINT "FK_division_employees_divisions_division_id" FOREIGN KEY (division_id) REFERENCES divisions (division_id) ON DELETE CASCADE,
    CONSTRAINT "FK_division_employees_employees_employee_id" FOREIGN KEY (employee_id) REFERENCES employees (employee_id) ON DELETE CASCADE
);

CREATE TABLE division_technologies (
    division_id bigint NOT NULL,
    technology_id bigint NOT NULL,
    CONSTRAINT "PK_division_technologies" PRIMARY KEY (division_id, technology_id),
    CONSTRAINT "FK_division_technologies_divisions_division_id" FOREIGN KEY (division_id) REFERENCES divisions (division_id) ON DELETE CASCADE,
    CONSTRAINT "FK_division_technologies_technologies_technology_id" FOREIGN KEY (technology_id) REFERENCES technologies (technology_id) ON DELETE CASCADE
);

CREATE TABLE company_addresses (
    company_address_id bigint GENERATED BY DEFAULT AS IDENTITY,
    building character varying(50) NOT NULL,
    street character varying(50) NOT NULL,
    address_contact character varying(50) NOT NULL,
    address_contact_no character varying(20) NOT NULL,
    opens character varying(25) NOT NULL,
    closes character varying(25) NOT NULL,
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    record_status character varying(50) NOT NULL,
    created_by bigint NOT NULL,
    created_on timestamp NOT NULL,
    updated_by bigint NOT NULL,
    updated_on timestamp NOT NULL,
    company_id bigint NOT NULL,
    address_type_id bigint NOT NULL,
    post_office_id bigint NOT NULL,
    CONSTRAINT "PK_company_addresses" PRIMARY KEY (company_address_id),
    CONSTRAINT "FK_company_addresses_address_types_address_type_id" FOREIGN KEY (address_type_id) REFERENCES address_types (address_type_id) ON DELETE CASCADE,
    CONSTRAINT "FK_company_addresses_companies_company_id" FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE,
    CONSTRAINT "FK_company_addresses_post_offices_post_office_id" FOREIGN KEY (post_office_id) REFERENCES post_offices (post_office_id) ON DELETE CASCADE
);

CREATE TABLE customer_addresses (
    customer_address_id bigint GENERATED BY DEFAULT AS IDENTITY,
    building character varying(50) NOT NULL,
    street character varying(50) NOT NULL,
    address_type character varying(50) NOT NULL,
    address_contact_no character varying(20) NOT NULL,
    latitude text NOT NULL,
    longitude text NOT NULL,
    is_default boolean NOT NULL,
    record_status character varying(50) NOT NULL,
    created_by bigint NOT NULL,
    created_on timestamp NOT NULL,
    updated_by bigint NOT NULL,
    updated_on timestamp NOT NULL,
    customer_id bigint NOT NULL,
    post_office_id bigint NOT NULL,
    CONSTRAINT "PK_customer_addresses" PRIMARY KEY (customer_address_id),
    CONSTRAINT "FK_customer_addresses_customers_customer_id" FOREIGN KEY (customer_id) REFERENCES customers (customer_id) ON DELETE CASCADE,
    CONSTRAINT "FK_customer_addresses_post_offices_post_office_id" FOREIGN KEY (post_office_id) REFERENCES post_offices (post_office_id) ON DELETE CASCADE
);

CREATE TABLE employee_addresses (
    employee_address_id bigint GENERATED BY DEFAULT AS IDENTITY,
    building character varying(50) NOT NULL,
    street character varying(50) NOT NULL,
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    record_status character varying(50) NOT NULL,
    created_by bigint NOT NULL,
    created_on timestamp NOT NULL,
    updated_by bigint NOT NULL,
    updated_on timestamp NOT NULL,
    employee_id bigint NOT NULL,
    address_type_id bigint NOT NULL,
    post_office_id bigint NOT NULL,
    CONSTRAINT "PK_employee_addresses" PRIMARY KEY (employee_address_id),
    CONSTRAINT "FK_employee_addresses_address_types_address_type_id" FOREIGN KEY (address_type_id) REFERENCES address_types (address_type_id) ON DELETE CASCADE,
    CONSTRAINT "FK_employee_addresses_employees_employee_id" FOREIGN KEY (employee_id) REFERENCES employees (employee_id) ON DELETE CASCADE,
    CONSTRAINT "FK_employee_addresses_post_offices_post_office_id" FOREIGN KEY (post_office_id) REFERENCES post_offices (post_office_id) ON DELETE CASCADE
);

INSERT INTO address_types (address_type_id, address_type_name, entity_name)
VALUES (1, 'BILLING', 'COMPANY');
INSERT INTO address_types (address_type_id, address_type_name, entity_name)
VALUES (2, 'SHIPPING', 'COMPANY');
INSERT INTO address_types (address_type_id, address_type_name, entity_name)
VALUES (3, 'WAREHOUSE', 'COMPANY');
INSERT INTO address_types (address_type_id, address_type_name, entity_name)
VALUES (4, 'WORK', 'EMPLOYEE');
INSERT INTO address_types (address_type_id, address_type_name, entity_name)
VALUES (5, 'PRESENT', 'EMPLOYEE');
INSERT INTO address_types (address_type_id, address_type_name, entity_name)
VALUES (6, 'PERMANENT', 'EMPLOYEE');
INSERT INTO address_types (address_type_id, address_type_name, entity_name)
VALUES (7, 'PRESENT', 'CUSTOMER');
INSERT INTO address_types (address_type_id, address_type_name, entity_name)
VALUES (8, 'PERMANENT', 'CUSTOMER');

INSERT INTO banks (bank_id, bank_name, record_status)
VALUES (1, 'STATE BANK OF INDIA', 'ACTIVE');
INSERT INTO banks (bank_id, bank_name, record_status)
VALUES (2, 'ICICI', 'ACTIVE');
INSERT INTO banks (bank_id, bank_name, record_status)
VALUES (3, 'HDFC BANK', 'ACTIVE');
INSERT INTO banks (bank_id, bank_name, record_status)
VALUES (4, 'AXIS BANK', 'ACTIVE');
INSERT INTO banks (bank_id, bank_name, record_status)
VALUES (5, 'UNION BANK OF INDIA', 'ACTIVE');

INSERT INTO certification_levels (certification_level_id, certification_level, level_no)
VALUES (1, 'BASIC', 1);
INSERT INTO certification_levels (certification_level_id, certification_level, level_no)
VALUES (2, 'INTERMEDIATE', 11);
INSERT INTO certification_levels (certification_level_id, certification_level, level_no)
VALUES (3, 'ADVANCED', 21);
INSERT INTO certification_levels (certification_level_id, certification_level, level_no)
VALUES (4, 'EXPERT', 41);

INSERT INTO company_levels (company_level_id, company_level, level_no)
VALUES (1, 'ROOT', 1);
INSERT INTO company_levels (company_level_id, company_level, level_no)
VALUES (2, 'MASTER', 11);
INSERT INTO company_levels (company_level_id, company_level, level_no)
VALUES (3, 'PARTNER', 21);
INSERT INTO company_levels (company_level_id, company_level, level_no)
VALUES (4, 'NATIONAL', 31);
INSERT INTO company_levels (company_level_id, company_level, level_no)
VALUES (5, 'ZONAL', 41);
INSERT INTO company_levels (company_level_id, company_level, level_no)
VALUES (6, 'STATE', 51);
INSERT INTO company_levels (company_level_id, company_level, level_no)
VALUES (7, 'DISTRICT', 61);
INSERT INTO company_levels (company_level_id, company_level, level_no)
VALUES (8, 'UNIT', 71);
INSERT INTO company_levels (company_level_id, company_level, level_no)
VALUES (9, 'DEALER', 81);

INSERT INTO company_types (company_type_id, company_type_name)
VALUES (1, 'HEAD OFFICE');
INSERT INTO company_types (company_type_id, company_type_name)
VALUES (2, 'BRANCH OFFICE');

INSERT INTO countries (country_id, country_code, country_name, record_status)
VALUES (1, 'IND', 'INDIA', 'ACTIVE');

INSERT INTO domains (domain_id, domain_name)
VALUES (1, 'SALES');
INSERT INTO domains (domain_id, domain_name)
VALUES (2, 'SERVICE');

INSERT INTO product_categories (product_category_id, product_category_name)
VALUES (1, 'LAPTOPS');
INSERT INTO product_categories (product_category_id, product_category_name)
VALUES (2, 'DESKTOPS');
INSERT INTO product_categories (product_category_id, product_category_name)
VALUES (3, 'FIREWALLS');

INSERT INTO qualification_levels (qualification_level_id, level_no, qualification_level)
VALUES (1, 1, 'PRIMARY');
INSERT INTO qualification_levels (qualification_level_id, level_no, qualification_level)
VALUES (2, 11, 'MATRICULATION');
INSERT INTO qualification_levels (qualification_level_id, level_no, qualification_level)
VALUES (3, 21, 'HIGH SCHOOL');
INSERT INTO qualification_levels (qualification_level_id, level_no, qualification_level)
VALUES (4, 31, 'DIPLOMA');
INSERT INTO qualification_levels (qualification_level_id, level_no, qualification_level)
VALUES (5, 41, 'GRADUATE');
INSERT INTO qualification_levels (qualification_level_id, level_no, qualification_level)
VALUES (6, 51, 'POST GRADUATE DIPLOMA');
INSERT INTO qualification_levels (qualification_level_id, level_no, qualification_level)
VALUES (7, 61, 'MASTERS');
INSERT INTO qualification_levels (qualification_level_id, level_no, qualification_level)
VALUES (8, 81, 'DOCTORATE');

INSERT INTO time_units (time_unit_id, time_unit)
VALUES (1, 'SECONDS');
INSERT INTO time_units (time_unit_id, time_unit)
VALUES (2, 'MILLI SECONDS');
INSERT INTO time_units (time_unit_id, time_unit)
VALUES (3, 'MICRO SECONDS');
INSERT INTO time_units (time_unit_id, time_unit)
VALUES (4, 'NANO SECONDS');
INSERT INTO time_units (time_unit_id, time_unit)
VALUES (5, 'MINUTES');
INSERT INTO time_units (time_unit_id, time_unit)
VALUES (6, 'HOURS');
INSERT INTO time_units (time_unit_id, time_unit)
VALUES (7, 'DAY');
INSERT INTO time_units (time_unit_id, time_unit)
VALUES (8, 'WEEK');
INSERT INTO time_units (time_unit_id, time_unit)
VALUES (9, 'MONTH');
INSERT INTO time_units (time_unit_id, time_unit)
VALUES (10, 'YEAR');

INSERT INTO verticals (vertical_id, vertical_name)
VALUES (1, 'IT');
INSERT INTO verticals (vertical_id, vertical_name)
VALUES (2, 'AUTOMOTIVE');

INSERT INTO product_types (product_type_id, product_category_id, product_type_name)
VALUES (1, 1, 'HP');
INSERT INTO product_types (product_type_id, product_category_id, product_type_name)
VALUES (2, 1, 'DELL');
INSERT INTO product_types (product_type_id, product_category_id, product_type_name)
VALUES (3, 1, 'LENOVO');
INSERT INTO product_types (product_type_id, product_category_id, product_type_name)
VALUES (4, 2, 'HP');
INSERT INTO product_types (product_type_id, product_category_id, product_type_name)
VALUES (5, 2, 'DELL');
INSERT INTO product_types (product_type_id, product_category_id, product_type_name)
VALUES (6, 2, 'LENOVO');
INSERT INTO product_types (product_type_id, product_category_id, product_type_name)
VALUES (7, 3, 'FORTINET');
INSERT INTO product_types (product_type_id, product_category_id, product_type_name)
VALUES (8, 3, 'SOPHOS');

INSERT INTO states (state_id, country_id, record_status, state_code, state_name)
VALUES (1, 1, 'ACTIVE', 'KRL', 'KERALA');

CREATE UNIQUE INDEX "IX_address_types_address_type_name_entity_name" ON address_types (address_type_name, entity_name);

CREATE UNIQUE INDEX "IX_banks_bank_name" ON banks (bank_name);

CREATE UNIQUE INDEX "IX_certification_levels_certification_level" ON certification_levels (certification_level);

CREATE UNIQUE INDEX "IX_certifications_certification_code" ON certifications (certification_code);

CREATE INDEX "IX_certifications_certification_level_id" ON certifications (certification_level_id);

CREATE UNIQUE INDEX "IX_certifications_certification_name" ON certifications (certification_name);

CREATE INDEX "IX_certifications_technology_id" ON certifications (technology_id);

CREATE UNIQUE INDEX "IX_companies_company_code" ON companies (company_code);

CREATE INDEX "IX_companies_company_level_id" ON companies (company_level_id);

CREATE INDEX "IX_companies_company_type_id" ON companies (company_type_id);

CREATE UNIQUE INDEX "IX_companies_gst" ON companies (gst);

CREATE INDEX "IX_company_addresses_address_type_id" ON company_addresses (address_type_id);

CREATE UNIQUE INDEX "IX_company_addresses_company_id_post_office_id_address_type_id" ON company_addresses (company_id, post_office_id, address_type_id);

CREATE INDEX "IX_company_addresses_post_office_id" ON company_addresses (post_office_id);

CREATE UNIQUE INDEX "IX_company_banks_account_no_ifsc" ON company_banks (account_no, ifsc);

CREATE INDEX "IX_company_banks_bank_id" ON company_banks (bank_id);

CREATE INDEX "IX_company_banks_company_id" ON company_banks (company_id);

CREATE UNIQUE INDEX "IX_company_contacts_company_id_contact_person_contact_number" ON company_contacts (company_id, contact_person, contact_number);

CREATE UNIQUE INDEX "IX_company_departments_company_id_department_name" ON company_departments (company_id, department_name);

CREATE UNIQUE INDEX "IX_company_domains_company_id_domain_id" ON company_domains (company_id, domain_id);

CREATE INDEX "IX_company_domains_domain_id" ON company_domains (domain_id);

CREATE UNIQUE INDEX "IX_company_levels_company_level" ON company_levels (company_level);

CREATE INDEX "IX_company_onboardings_company_id" ON company_onboardings (company_id);

CREATE INDEX "IX_company_onboardings_company_level_id" ON company_onboardings (company_level_id);

CREATE UNIQUE INDEX "IX_company_onboardings_entity_email" ON company_onboardings (entity, email);

CREATE UNIQUE INDEX "IX_company_onboardings_entity_mobile" ON company_onboardings (entity, mobile);

CREATE UNIQUE INDEX "IX_company_onboardings_tracking_id" ON company_onboardings (tracking_id);

CREATE UNIQUE INDEX "IX_company_types_company_type_name" ON company_types (company_type_name);

CREATE UNIQUE INDEX "IX_company_verticals_company_id_vertical_id" ON company_verticals (company_id, vertical_id);

CREATE INDEX "IX_company_verticals_vertical_id" ON company_verticals (vertical_id);

CREATE INDEX "IX_complaints_customer_id" ON complaints (customer_id);

CREATE INDEX "IX_complaints_product_type_id" ON complaints (product_type_id);

CREATE UNIQUE INDEX "IX_countries_country_code" ON countries (country_code);

CREATE UNIQUE INDEX "IX_countries_country_name" ON countries (country_name);

CREATE UNIQUE INDEX "IX_customer_addresses_customer_id_post_office_id_address_type" ON customer_addresses (customer_id, post_office_id, address_type);

CREATE INDEX "IX_customer_addresses_post_office_id" ON customer_addresses (post_office_id);

CREATE UNIQUE INDEX "IX_customer_banks_account_no_ifsc" ON customer_banks (account_no, ifsc);

CREATE INDEX "IX_customer_banks_bank_id" ON customer_banks (bank_id);

CREATE INDEX "IX_customer_banks_customer_id" ON customer_banks (customer_id);

CREATE UNIQUE INDEX "IX_customers_aadhar" ON customers (aadhar);

CREATE INDEX "IX_customers_company_id" ON customers (company_id);

CREATE UNIQUE INDEX "IX_customers_customer_code" ON customers (customer_code);

CREATE UNIQUE INDEX "IX_customers_email" ON customers (email);

CREATE UNIQUE INDEX "IX_customers_gst" ON customers (gst);

CREATE UNIQUE INDEX "IX_customers_mobile" ON customers (mobile);

CREATE UNIQUE INDEX "IX_customers_pan" ON customers (pan);

CREATE UNIQUE INDEX "IX_designations_designation_code" ON designations (designation_code);

CREATE UNIQUE INDEX "IX_designations_designation_name" ON designations (designation_name);

CREATE UNIQUE INDEX "IX_districts_district_code" ON districts (district_code);

CREATE UNIQUE INDEX "IX_districts_district_name" ON districts (district_name);

CREATE INDEX "IX_districts_state_id" ON districts (state_id);

CREATE INDEX "IX_division_employees_division_id" ON division_employees (division_id);

CREATE UNIQUE INDEX "IX_division_employees_employee_id_division_id" ON division_employees (employee_id, division_id);

CREATE INDEX "IX_division_technologies_technology_id" ON division_technologies (technology_id);

CREATE UNIQUE INDEX "IX_divisions_department_id_division_name" ON divisions (department_id, division_name);

CREATE UNIQUE INDEX "IX_domains_domain_name" ON domains (domain_name);

CREATE INDEX "IX_employee_addresses_address_type_id" ON employee_addresses (address_type_id);

CREATE UNIQUE INDEX "IX_employee_addresses_employee_id_post_office_id_address_type_~" ON employee_addresses (employee_id, post_office_id, address_type_id);

CREATE INDEX "IX_employee_addresses_post_office_id" ON employee_addresses (post_office_id);

CREATE UNIQUE INDEX "IX_employee_banks_account_no_ifsc" ON employee_banks (account_no, ifsc);

CREATE INDEX "IX_employee_banks_bank_id" ON employee_banks (bank_id);

CREATE INDEX "IX_employee_banks_employee_id" ON employee_banks (employee_id);

CREATE INDEX "IX_employee_certifications_certification_id" ON employee_certifications (certification_id);

CREATE UNIQUE INDEX "IX_employee_certifications_employee_id_certification_id" ON employee_certifications (employee_id, certification_id);

CREATE UNIQUE INDEX "IX_employee_qualifications_employee_id_specialization_id" ON employee_qualifications (employee_id, specialization_id);

CREATE INDEX "IX_employee_qualifications_specialization_id" ON employee_qualifications (specialization_id);

CREATE INDEX "IX_employee_qualifications_time_unit_id" ON employee_qualifications (time_unit_id);

CREATE INDEX "IX_employee_work_experiences_designation_id" ON employee_work_experiences (designation_id);

CREATE INDEX "IX_employee_work_experiences_employee_id" ON employee_work_experiences (employee_id);

CREATE INDEX "IX_employee_work_experiences_vertical_id" ON employee_work_experiences (vertical_id);

CREATE UNIQUE INDEX "IX_employees_aadhar" ON employees (aadhar);

CREATE INDEX "IX_employees_company_id" ON employees (company_id);

CREATE INDEX "IX_employees_designation_id" ON employees (designation_id);

CREATE UNIQUE INDEX "IX_employees_email" ON employees (email);

CREATE UNIQUE INDEX "IX_employees_employee_code" ON employees (employee_code);

CREATE UNIQUE INDEX "IX_employees_mobile" ON employees (mobile);

CREATE UNIQUE INDEX "IX_employees_pan" ON employees (pan);

CREATE INDEX "IX_onboarding_transactions_onboarding_id" ON onboarding_transactions (onboarding_id);

CREATE UNIQUE INDEX "IX_onboarding_transactions_tracking_id" ON onboarding_transactions (tracking_id);

CREATE UNIQUE INDEX "IX_post_offices_district_id_post_office_name" ON post_offices (district_id, post_office_name);

CREATE UNIQUE INDEX "IX_product_categories_product_category_name" ON product_categories (product_category_name);

CREATE UNIQUE INDEX "IX_product_types_product_category_id_product_type_name" ON product_types (product_category_id, product_type_name);

CREATE UNIQUE INDEX "IX_qualification_levels_qualification_level" ON qualification_levels (qualification_level);

CREATE UNIQUE INDEX "IX_qualifications_qualification_code" ON qualifications (qualification_code);

CREATE INDEX "IX_qualifications_qualification_level_id" ON qualifications (qualification_level_id);

CREATE UNIQUE INDEX "IX_qualifications_qualification_name" ON qualifications (qualification_name);

CREATE UNIQUE INDEX "IX_specializations_qualification_id_specialization_name" ON specializations (qualification_id, specialization_name);

CREATE INDEX "IX_states_country_id" ON states (country_id);

CREATE UNIQUE INDEX "IX_states_state_code" ON states (state_code);

CREATE UNIQUE INDEX "IX_states_state_name" ON states (state_name);

CREATE UNIQUE INDEX "IX_technologies_technology_name" ON technologies (technology_name);

CREATE UNIQUE INDEX "IX_time_units_time_unit" ON time_units (time_unit);

CREATE UNIQUE INDEX "IX_verticals_vertical_name" ON verticals (vertical_name);

SELECT setval(
    pg_get_serial_sequence('address_types', 'address_type_id'),
    GREATEST(
        (SELECT MAX(address_type_id) FROM address_types) + 1,
        nextval(pg_get_serial_sequence('address_types', 'address_type_id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('banks', 'bank_id'),
    GREATEST(
        (SELECT MAX(bank_id) FROM banks) + 1,
        nextval(pg_get_serial_sequence('banks', 'bank_id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('certification_levels', 'certification_level_id'),
    GREATEST(
        (SELECT MAX(certification_level_id) FROM certification_levels) + 1,
        nextval(pg_get_serial_sequence('certification_levels', 'certification_level_id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('company_levels', 'company_level_id'),
    GREATEST(
        (SELECT MAX(company_level_id) FROM company_levels) + 1,
        nextval(pg_get_serial_sequence('company_levels', 'company_level_id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('company_types', 'company_type_id'),
    GREATEST(
        (SELECT MAX(company_type_id) FROM company_types) + 1,
        nextval(pg_get_serial_sequence('company_types', 'company_type_id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('countries', 'country_id'),
    GREATEST(
        (SELECT MAX(country_id) FROM countries) + 1,
        nextval(pg_get_serial_sequence('countries', 'country_id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('domains', 'domain_id'),
    GREATEST(
        (SELECT MAX(domain_id) FROM domains) + 1,
        nextval(pg_get_serial_sequence('domains', 'domain_id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('product_categories', 'product_category_id'),
    GREATEST(
        (SELECT MAX(product_category_id) FROM product_categories) + 1,
        nextval(pg_get_serial_sequence('product_categories', 'product_category_id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('qualification_levels', 'qualification_level_id'),
    GREATEST(
        (SELECT MAX(qualification_level_id) FROM qualification_levels) + 1,
        nextval(pg_get_serial_sequence('qualification_levels', 'qualification_level_id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('time_units', 'time_unit_id'),
    GREATEST(
        (SELECT MAX(time_unit_id) FROM time_units) + 1,
        nextval(pg_get_serial_sequence('time_units', 'time_unit_id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('verticals', 'vertical_id'),
    GREATEST(
        (SELECT MAX(vertical_id) FROM verticals) + 1,
        nextval(pg_get_serial_sequence('verticals', 'vertical_id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('product_types', 'product_type_id'),
    GREATEST(
        (SELECT MAX(product_type_id) FROM product_types) + 1,
        nextval(pg_get_serial_sequence('product_types', 'product_type_id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('states', 'state_id'),
    GREATEST(
        (SELECT MAX(state_id) FROM states) + 1,
        nextval(pg_get_serial_sequence('states', 'state_id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20221101092401_Initial', '6.0.9');

COMMIT;

