version: '3.6'
services:
  db:
    image: postgres:14.5-bullseye
    container_name: ompgsqlone
    environment:
      - container_name=ompgsqlone
      - POSTGRES_USER=onlinemagic
      - POSTGRES_DB=identityone
      - POSTGRES_PASSWORD=onlinemagic
      - PGDATA=/var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes: 
      - /pgdata/:/var/lib/postgresql/data


  reverseproxy:
    build: ./nginx/
    container_name: reverseproxy 
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    container_name: certbot

    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email "${CERT_MAIL}"  ${DOMAIN}  --agree-tos

  # reverseproxy:
      
  #     build: ./nginx/
  #     container_name: reverseproxy
  #     ports:
  #       - "80:80"
  #       - "443:443"
  #     volumes:
  #       - /etc/nginx/ssl/certificate.crt:/etc/nginx/ssl/certificate.crt
  #       - /etc/nginx/ssl/private.key:/etc/nginx/ssl/private.key
  #       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  identityone:
    build: 
      context: ./IdentityOne/
    container_name: identityone
    environment:
      - ASPNETCORE_URLS=http://+:5000
      # - "ConnectionStrings:EfConn=\"Server=ompgsqlone;Port=5432;Database=identityone;User Id=onlinemagic;Password=onlinemagic;\""
      # - "DapperConn:PgSql=\"User ID=onlinemagic;Password=onlinemagic;Host=ompgsqlone;Port=5432;Database=identityone;Pooling=true;Timeout=300;CommandTimeout=300;KeepAlive=300\""      
       
    depends_on:
      - db
    volumes: 
      - ./IdentityOne/appsettings.json:/app/appsettings.json
      - ./Keys/private-key.pem:/app/private-key.pem
      - ./Keys/public-key.pem:/app/public-key.pem

    ports:
      - '5001:5000'

  omadmin:
    build:
      context: ./OmAdmin/
    container_name: omadmin
    
    depends_on:
      - db
    # env_file:
    #   - ./OmAdmin/.env
    environment:
      - ASPNETCORE_URLS=http://+:5000
      # - "ConnectionStrings:EfConn=\"Server=ompgsqlone;Port=5432;Database=identityone;User Id=onlinemagic;Password=onlinemagic;\""
      # - "DapperConn:PgSql=\"User ID=onlinemagic;Password=onlinemagic;Host=ompgsqlone;Port=5432;Database=identityone;Pooling=true;Timeout=300;CommandTimeout=300;KeepAlive=300\""
      # - "ApiUrls:Identity=http://identityone:5000"
      # - "ApiUrls:Admin=http://omadminapi:5000"
    volumes: 
      - ./OmAdmin/appsettings.json:/app/appsettings.json
      - ./Keys/public-key.pem:/app/public-key.pem

    ports:
      - '5000:5000'

  omadminapi:
    build:
      context: ./OmAdminApi/
    container_name: omadminapi
    environment:
      - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - db
    volumes: 
      - ./OmAdminApi/appsettings.json:/app/appsettings.json
      - ./Keys/public-key.pem:/app/public-key.pem
    ports:
      - '5002:5000'

  omcompany:
    build:
      context: ./OmCompany/
    container_name: omcompany
    environment:
      - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - db
    volumes: 
      - ./OmCompany/appsettings.json:/app/appsettings.json
      - ./Keys/public-key.pem:/app/public-key.pem
    ports:
      - '5003:5000'
  omcustomer:
    build:
      context: ./OmCustomer/
    container_name: omcustomer
    environment:
      - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - db
    volumes: 
      - ./OmCustomer/appsettings.json:/app/appsettings.json
      - ./Keys/public-key.pem:/app/public-key.pem
    ports:
      - '5004:5000'
  omonboard:
    build: ./OmOnboard/
    container_name: omonboard
    environment:
      - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - db
    volumes: 
      - ./OmOnboard/appsettings.json:/app/appsettings.json
      - ./Keys/public-key.pem:/app/public-key.pem
    ports:
      - '5005:5000'

  omcarepackapi:
    build: ./OmCarePackApi/
    container_name: omcarepackapi
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - RUNNER=OmCarePackApi.dll
    depends_on:
      - db
    volumes: 
      - ./OmCarePackApi/appsettings.json:/app/appsettings.json
      - ./Keys/public-key.pem:/app/public-key.pem
    ports:
      - '5005:5000'